<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carte interactive avec Leaflet</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <style>
        #map { /* Style pour le conteneur de la carte */
            height: 600px;
            z-index:1;
        }
    </style>
</head>
<body>

    <h2>Prochaines ballades</h2>
    <div id='ad_list'>
        <?php

            $count = 0;
            foreach($adList as $ad) :
                // Limiter à 10 annonces
                if ($count >= 10) {
                    break; // Sortir de la boucle foreach si on a atteint 10 annonces
                }
                ?>
                <div class="ad">
                    <h3><?= $ad->getTitle() ?></h3>
                    <p>Date : <?= $ad->getDate()->format('d-m-Y') ?></p>
                    <p> <?= $ad->getText() ?> </p>
                    <p> <?= $ad->getCityId() ?> </p>
                    <p> Longitude : <?= $ad->getLongitude() ?> </p>
                    <p> Latitude :  <?= $ad->getLatitude() ?> </p>
                </div>
            <?php
            // Incrémenter le compteur
            $count++;
            endforeach;
        ?>
          
    </div>
    <h2>Derniers Parcs Ajoutés</h2>

    <p>Liste des parcs ici</p>
    <div id="map"></div> <!-- Conteneur pour la carte -->
    <div class="popupAdClicked">
        <button class='closeBtn'>Close</button>
        <h3 class = "titleAdClicked"></h3>
        <p class = "textAdClicked"></p>
        <p class = "cityAdClicked"></p>
    </div>
    <script>
        //array_map parcours chaque element et leur applique cette fonction de rappel qui transforme chaque objet en un tabAss
        var adData = <?= json_encode(array_map(function($ad) {
            return [
                'id' => $ad->getId(),
                'title' => $ad->getTitle(),
                'latitude' => $ad->getLatitude(),
                'longitude' => $ad->getLongitude(),
                'date' => $ad->getDate(),
                'text' => $ad->getText()
            ];
        }, $adList)); ?>;
    </script>
    <!-- Inclure Leaflet JavaScript -->
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="../src/JS/index.js"></script> <!-- Fichier JavaScript pour l'initialisation de la carte -->
</body>
</html>
