<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carte interactive avec Leaflet</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <style>
        #map { /* Style pour le conteneur de la carte */
            height: 600px;
            z-index:1;
        }
    </style>
</head>
<body>
<h2 class='text-center'>Derniers Posts</h2>

    <h3 >Rendez-vous</h3>
    <div id='walk-list'>
        <?php

            $count = 0;
            foreach($walkList as $walk) :
                // Limiter à 10 annonces
                if ($count >= 10) {
                    break; // Sortir de la boucle foreach si on a atteint 10 annonces
                }
                ?>
                <div class="walk">
                    <h3><?= $walk->getTitle() ?></h3>
                    <p>Date : <?= $walk->getDate()->format('d-m-Y') ?></p>
                    <p> <?= $walk->getText() ?> </p>
                    <p> <?= $walk->getCityId() ?> </p>
                    <p> Longitude : <?= $walk->getLongitude() ?> </p>
                    <p> Latitude :  <?= $walk->getLatitude() ?> </p>
                </div>
            <?php
            // Incrémenter le compteur
            $count++;
            endforeach;
        ?>
          
    </div>
    <h3>Répertoire de randos</h3>
    <div id="map"></div> <!-- Conteneur pour la carte -->
    <div class="popup-walkClicked">
        <button class='btn-close close-walkClicked'>Close</button>
        <h3 class = "title-walkClicked"></h3>
        <p class = "text-walkClicked"></p>
        <p class = "city-walkClicked"></p>
    </div>
    <script>
        //Pour accès Format Json au traitement JS 
        var walkData = <?= json_encode(array_map(function($walk) {
            return [
                'id' => $walk->getWalkId(),
                'title' => $walk->getTitle(),
                'latitude' => $walk->getLatitude(),
                'longitude' => $walk->getLongitude(),
                'date' => $walk->getDate(),
                'text' => $walk->getText()
            ];
        }, $walkList)); ?>;
    </script>
    <!-- Inclure Leaflet JavaScript -->
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="../src/JS/index.js"></script> <!-- Fichier JavaScript pour l'initialisation de la carte -->
</body>
</html>
