<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    IMPORTER LOCALISATIONS
    <form action="" method='POST' >
        <input type='submit' name='import-regions'value='add-Regions'/>
    </form>
    <form action="" method='POST' >
        <input type='submit' name='import-departments' value="add-Dpt"/>
    </form>
    <form action="" method='POST' >
        <input type='submit' name='import-cities' value = "add-Cities"/>
    </form>

</body>
</html>