<select name='department' id='department' required>
            <option value="">Choisir un Département</option>
            <!-- Ajoutez ici vos options pour le département -->
        </select>
        <label for="city">Choisir une ville :</label>
        <input type="text" name="search" id="citySearch" placeholder="Rechercher une ville" required>
        <div id="cityResults" class="autocomplete-results"></div> <!-- Div pour afficher les résultats -->

        <script src='../src/JS/location.js'></script>