<select name='department' id='department' required>
    <option value="">Choisir un Département</option>
</select>
<label for="city">Choisir une ville :</label>
<input type="text" name="cityNameSearch" id="cityNameSearch" value="" placeholder="Rechercher une ville" required>
<input type="hidden" name="zipcode" id = "zipcode" value = "">
<div id="cityResults" class="autocomplete-results"></div>

<script src='../Assets/JS/location.js'></script>