

<link rel="stylesheet" href="../../Assets/CSS/postAd.css">

<div class="popup">
    <button class='btn-close close-postHike'>close</button>
    <?php if (isset($_SESSION['User']) && !empty($_SESSION['User'])): ?>
        <form action="" method="POST" class="form-post-hike">
            <input type="text" name="title" placeholder="Titre de l'annonce" required>
            <input type="date" id="hike-date" name="date" placeholder="Date de l'annonce" required>
            <input type="time" id="hike-time" name="time" placeholder="Heure de l'annonce" required>
            <input type="number" id="hike-elevation" name = "elevation" required placeholder="dénivelé"/>
            <input type="number" id="hike-distance" name = "distance" required placeholder="distance"/>

            <input type="text" id="hike-dificulties" name="dificulties" />
            

            <!--Point d'eau -->
            <p>Point d'eau?</p>
            <input type="radio" id="yes" name="water_point" value="yes">
            <label for="yes">Oui</label><br>
            <input type="radio" id="no" name="water_point" value="no">
            <label for="no">Non</label><br>

            <textarea name="text" placeholder="Texte de l'annonce" rows="8" required></textarea>
            
            <?php require 'Vues/location.phtml' ?> 

            <input type="submit" name="post_hike" value="Ajouter l'annonce">
        </form>

    <?php else: ?>
        <p> Merci de vous <a href='?page=login'>connecter</a> ou de  <a href='?page=register'>créer un compte</a> </p>
    <?php endif; ?>
</div>


