<!-- RECOIT LA LISTE DES ANNONCES PAR CONTROLLEUR walk_list_ctrl -->

<!-- SEULEMENT SI PAGE CONSULTWALKS - PAS HOME -->
<?php if(isset($_GET['page']) && $_GET['page'] != "home"): ?>
    <a href="#" class='post-ad-link'>Proposer un RDV</a>
    <!-- Proposer un RDV -->
    <div class="post-ad-box invisible">
        <?php require 'Controllers/walks/post_walk_ctrl.php'; ?> 
    </div>
<?php endif; ?>
<section class="validation_or_error">
    <div id="success-message"></div>
</section>
<h3>RDVS Marches</h3>

<!-- Liste des prochains Walk -->
<?php require 'walk_list.phtml'; ?>

<!-- SEULEMENT SI PAGE CONSULTWALKS - PAS HOME -->
<?php if(isset($_GET['page']) && $_GET['page'] != "home"): ?>
    <!-- Affichage de la liste des régions -->
    <?php require __DIR__ . '/../location/region_list.phtml'; ?>
<?php endif; ?>

<!-- Si pas home, Map avec les marches prevues-->
<?php if(isset($_GET['page']) && $_GET['page'] != "home"): ?>
    <div id="map"></div>
    <!-- Popup de l'annonce cliquée -->
    <?php require 'walk_details.phtml'; ?>
    <!-- SINON , map avec le melange des rando et marches -->
<?php endif; ?>

<script src="../../Assets/JS/postAd.js"></script>
<script src="../Assets/JS/walkData.js"></script> <!-- Fichier JavaScript pour l'initialisation de la carte -->
