<!-- RECOIT LA LISTE DES ANNONCES PAR CONTROLLEUR walk_list_ctrl -->

<!-- SEULEMENT SI PAGE CONSULTWALKS - PAS HOME -->
<?php if(isset($_GET['page']) && $_GET['page'] != "home"): ?>
    <a href="#" class='post-walk-link'>Proposer un RDV</a>
    <!-- Proposer un RDV -->
    <div class="post-walk-box invisible">
        <?php require 'Controllers/walks/post_walk_ctrl.php'; ?> 
    </div>
<?php endif; ?>

<h3>RDVS Marches</h3>
<!-- Liste des prochains Walk -->
<?php require 'walk_list.phtml'; ?>

<!-- SEULEMENT SI PAGE CONSULTWALKS - PAS HOME -->
<?php if(isset($_GET['page']) && $_GET['page'] != "home"): ?>
    <!-- Affichage de la liste des régions -->
    <?php require __DIR__ . '/../location/region_list.phtml'; ?>
<?php endif; ?>

<!-- SEULEMENT SI PAGE HOME - PAS CONSULTWALKS -->
<?php if(isset($_GET['page']) && $_GET['page'] == "home"): ?>
    <h3>Répertoire de randos</h3>
    <!-- Contenu spécifique pour la page Home -->
    ...A suivre ...
<?php endif; ?>

<div id="map"></div>
<!-- Popup de l'annonce cliquée -->
<?php require 'walk_details.phtml'; ?>

<script src="../../Assets/JS/postWalk.js"></script>
<script src="../Assets/JS/index.js"></script> <!-- Fichier JavaScript pour l'initialisation de la carte -->
