

<link rel="stylesheet" href="../../Assets/CSS/postWalk.css">

<div class="popup">
    <button class='btn-close close-postWalk' >close</button>
    <?php if (isset($_SESSION['User']) && !empty($_SESSION['User'])): ?>
        <form action="" method="POST" class="form-post-walk">
    <input type="text" name="title" placeholder="Titre de l'annonce" required>
    <input type="date" id="date" name="date" placeholder="Date de l'annonce" required>
    <input type="time" id="time" name="time" placeholder="Heure de l'annonce" required>
    <textarea name="text" placeholder="Texte de l'annonce" rows="8" required></textarea>
    
    <?php require 'Vues/location.phtml' ?>

    <input type="submit" name="post_walk" value="Ajouter l'annonce">
</form>

    <?php else: ?>
        <p> Merci de vous <a href='?page=login'>connecter</a> ou de  <a href='?page=register'>créer un compte</a> </p>
    <?php endif; ?>
</div>


