<form action="" method="POST" class="registration-form">
<button class='btn-close close-register' >close</button>

<?php if (isset($_SESSION['success-message'])): ?>
        <p class="success-message"><?php echo $_SESSION['success-message']; ?></p>
        <?php unset($_SESSION['success-message']); ?>
    <?php endif; ?>
    <div>
        <label for="email">Email : </label>
        <input type="mail" id='email' name ='email'>
    </div>
    <div>
        <label for="password">Mot de passe :</label>
        <input type="password" id="password" name="password" required>
    </div>
    <div>
        <label for="name">Surnom :</label>
        <input type="text" id="name" name="name" required>
    </div>
    <div>
        <label for="phone">Téléphone :</label>
        <input type="tel" id="phone" name="phone" required>
    </div>

    <!-- Champs avec valeurs par défaut -->
    <input type="hidden" name="role" value="user">
    <input type="hidden" name="signup-date" value="<?php echo date('Y-m-d H:i:s'); ?>">
    <?php require 'Vues/location.phtml' ?>
    <div>
        <input type="submit" name="confirm_registration" value="Valider">
    </div>
</form>
<script src="../../Assets/JS/register.js"></script>
